name: Jay Huie
title: thecapacity
description: "Learn by Doing"
author: wjhuie
repository: thecapacity/thecapacity.github.io
url: "http://thecapacity.org"
timezone: America/New_York
encoding: UTF-8
branch: "master"

# Social metadata (JSON-LD)
social:
  name: Jay Huie
  links:
    - https://twitter.com/wjhuie
    - https://www.linkedin.com/in/wjhuie
    - https://github.com/thecapacity

twitter:
    username: "@wjhuie"

kramdown:
  input: GFM

#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "posts"
